# Common environment variables
x-environment: &common-env # Vector model name
  EMBEDDING_MODEL: Pro/BAAI/bge-m3
  # Vector service address
  EMBEDDING_URL: https://api.siliconflow.cn/v1/embeddings
  # Vector service API key
  EMBEDDING_APIKEY: sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  # Vector dimensions
  EMBEDDING_DIMENSIONS: 1024
  # Master key
  MEILI_MASTER_KEY: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

services:
  # Meilisearch search engine service
  meilisearch:
    image: getmeili/meilisearch:latest
    restart: always
    environment: *common-env
    # ports:
    #   - "7700:7700"
    volumes:
      - meili_data:/meili_data

  # DocBase knowledge sync system
  docbase:
    depends_on:
      - meilisearch
      - dufs
    image: gonorth/docbase:latest
    environment:
      <<: *common-env
      INIT_PATH: /data
      MEILI_URL: http://meilisearch:7700
    volumes:
      - data:/data
    ports:
      - "3000:3000"

volumes:
  data:
  meili_data:
